name: oasth
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  bottom_navy_bar: ^6.1.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  url_launcher: ^6.3.2
  easy_localization: ^3.0.8
  location: ^8.0.1
  carousel_slider: ^5.1.2
  flutter_map_marker_cluster: ^8.2.2
  flutter_map_location_marker: ^10.2.0
  shared_preferences: ^2.5.4
  maps_launcher: ^3.0.0+1



dependency_overrides:
  win32: ^5.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/icons/